name: netflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bordered_text: ^2.0.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  share_it: ^0.7.0
  video_player: ^2.8.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "icon/icon.png" 
  android: true
  
flutter:
  uses-material-design: true
